apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: zylkerkart
spec:
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      nodeSelector:
        role: app
      containers:
      - name: authentication-service
        image: impazhani/zylkerkart-authentication-service:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: mysqluser
        - name: DB_PASS
          value: mypass
        - name: DB_SCHEMA
          value: ecommerce_app_database
        - name: REDIS_HOST
          value: redis-cache
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: mypass
        - name: ACTIVE_PROFILE
          value: dev
        - name: PORT
          value: "7000"
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/home/apm/apminsight-javaagent.jar -Dapminsight.application.name=zylkerkart-authentication-service"
        - name: S247_LICENSE_KEY
          value: "eu_23c74cf5bd4e2ecf8c60bf1fabcb84b2"
        ports:
        - containerPort: 7000
        volumeMounts:
        - name: s247agent
          mountPath: /home/apm
      initContainers:
      - name: agent-copy-init
        image: site24x7/apminsight-javaagent:latest
        imagePullPolicy: IfNotPresent
        command: ['cp', '-r', '/opt/site24x7/.', '/home/apm']
        volumeMounts:
        - name: s247agent
          mountPath: /home/apm
      volumes:
      - name: s247agent
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: zylkerkart
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
