apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-service
  namespace: zylkerkart
spec:
  selector:
    matchLabels:
      app: authentication-service
  template:
    metadata:
      labels:
        app: authentication-service
    spec:
      nodeSelector:
        role: app
      containers:
      - name: authentication-service
        image: impazhani/zylkerkart-authentication-service:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: mysqluser
        - name: DB_PASS
          value: mypass
        - name: DB_SCHEMA
          value: ecommerce_app_database
        - name: REDIS_HOST
          value: redis-cache
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: mypass
        - name: ACTIVE_PROFILE
          value: dev
        - name: PORT
          value: "7000"
        ports:
        - containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: zylkerkart
spec:
  selector:
    app: authentication-service
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
