apiVersion: apps/v1
kind: Deployment
metadata:
  name: common-data-service
  namespace: zylkerkart
spec:
  replicas: 2
  selector:
    matchLabels:
      app: common-data-service
  template:
    metadata:
      labels:
        app: common-data-service
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - common-data-service
              topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: app
      containers:
      - name: common-data-service
        image: impazhani/zylkerkart-common-data-service:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1000m"
            memory: "1024Mi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: mysqluser
        - name: DB_PASS
          value: mypass
        - name: DB_SCHEMA
          value: ecommerce_app_database
        - name: REDIS_HOST
          value: redis-cache
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: mypass
        - name: ACTIVE_PROFILE
          value: dev
        - name: PORT
          value: "9000"
        - name: REACT_CLIENT_URL
          value: "*"  # Allow CORS from anywhere in K8s
        - name: JAVA_TOOL_OPTIONS
          value: "-javaagent:/home/apm/apminsight-javaagent.jar -Dapminsight.application.name=zylkerkart-common-data-service"
        - name: S247_LICENSE_KEY
          value: "<YOUR_SITE24X7_LICENSE_KEY>"
        - name: SPRING_JPA_HIBERNATE_DDL_AUTO
          value: "update"
        ports:
        - containerPort: 9000
        volumeMounts:
        - name: s247agent
          mountPath: /home/apm
      initContainers:
      - name: agent-copy-init
        image: site24x7/apminsight-javaagent:latest
        imagePullPolicy: IfNotPresent
        command: ['cp', '-r', '/opt/site24x7/.', '/home/apm']
        volumeMounts:
        - name: s247agent
          mountPath: /home/apm
      volumes:
      - name: s247agent
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: common-data-service
  namespace: zylkerkart
spec:
  selector:
    app: common-data-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
