apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway-service
  namespace: zylkerkart
spec:
  selector:
    matchLabels:
      app: payment-gateway-service
  template:
    metadata:
      labels:
        app: payment-gateway-service
    spec:
      containers:
      - name: payment-gateway-service
        image: impazhani/zylkerkart-payment-gateway-service:latest
        imagePullPolicy: Always
        env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: mysqluser
        - name: DB_PASS
          value: mypass
        - name: DB_SCHEMA
          value: ecommerce_app_database
        - name: REDIS_HOST
          value: redis-cache
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: mypass
        - name: ACTIVE_PROFILE
          value: dev
        - name: PORT
          value: "9050"
        ports:
        - containerPort: 9050
---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-service
  namespace: zylkerkart
spec:
  selector:
    app: payment-gateway-service
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
