apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-gateway-service
  namespace: zylkerkart
spec:
  selector:
    matchLabels:
      app: payment-gateway-service
  template:
    metadata:
      labels:
        app: payment-gateway-service
    spec:
      nodeSelector:
        role: app
      containers:
      - name: payment-gateway-service
        image: impazhani/zylkerkart-payment-gateway-service:eks-v2
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "250m"
            memory: "256Mi"
        env:
        - name: DB_HOST
          value: mysql-db
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: mysqluser
        - name: DB_PASS
          value: mypass
        - name: DB_SCHEMA
          value: ecommerce_app_database
        - name: REDIS_HOST
          value: redis-cache
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          value: mypass
        - name: ACTIVE_PROFILE
          value: dev
        - name: PORT
          value: "9050"
        - name: APM_APP_NAME
          value: "zylkerkart-payment-gateway-service"
        - name: S247_LICENSE_KEY
          value: "<YOUR_SITE24X7_LICENSE_KEY>"
        - name: APP_RUN_COMMAND
          value: "uvicorn app:app --host 0.0.0.0 --port 9050"
        - name: PYTHONPATH
          value: "/home/apm/agent:/home/apm/agent/apminsight/bootstrap"
        command: ["/bin/sh", "-c", "/home/apm/agent_start.sh"]
        ports:
        - containerPort: 9050
        volumeMounts:
        - name: s247agent
          mountPath: /home/apm
      initContainers:
      - name: agent-copy
        image: site24x7/apminsight-pythonagent:latest
        imagePullPolicy: IfNotPresent
        command: ['cp', '-r', '/opt/site24x7/.', '/home/apm']
        volumeMounts:
        - name: s247agent
          mountPath: /home/apm
      volumes:
      - name: s247agent
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: payment-gateway-service
  namespace: zylkerkart
spec:
  selector:
    app: payment-gateway-service
  ports:
    - protocol: TCP
      port: 9050
      targetPort: 9050
